name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                operating-system: [ubuntu-latest, macos-latest, windows-latest]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js latest
              uses: actions/setup-node@v4
              with:
                  # hard code until this bug is fixed with Node 22: https://github.com/nodejs/node/issues/52682
                  node-version: 21
            - name: install
              run: |
                  npm clean-install
                  npx playwright install
            - name: check formatting
              run: |
                  npm run prettier
            - name: build
              run: |
                  npm run clean
                  npm run build
            - name: test
              run: |
                  npm test
            - name: check repo is clean
              # skip this check in windows for now, as the build outputs may get slightly modified in Windows, which we want to fix.
              if: runner.os != 'Windows'
              run: |
                  git diff
                  git add . && git diff --quiet && git diff --cached --quiet
              env:
                  CI: true
